---
- name: Install common required packages
  apt:
    pkg:
    - curl
    - build-essential
    - git
    - python3-pip
    update_cache: yes
    state: latest

- name: Add GitHub SSH key
  copy:
    src: cgus-bot-key.private_key
    dest: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Configure SSH to use Ansible key for github.com
  template:
    src: ssh_config.j2
    dest: "/home/{{ ansible_user }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- include_tasks: docker.yml
